version: '3.9'

services:
  backend:
    build: ./backend
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_salas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/docker-init/:/docker-entrypoint-initdb.d/  # scripts de inicialización

volumes:
  mysql-data:
